"""Add UserActivity model and relationship

Revision ID: 60887bf9fd3f
Revises: 7fc575a9bf3e
Create Date: 2025-02-11 23:38:41.388799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60887bf9fd3f'
down_revision: Union[str, None] = '7fc575a9bf3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.Column('session_duration', sa.Integer(), nullable=True),
    sa.Column('browser', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activities_id'), 'user_activities', ['id'], unique=False)
    op.drop_index('ix_user_activity_id', table_name='user_activity')
    op.drop_table('user_activity')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'STAFF', 'MEMBER', name='userrole'),
               type_=sa.Enum('ADMIN', 'STAFF', 'MEMBER', name='userrole', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'STAFF', 'MEMBER', name='userrole', native_enum=False),
               type_=postgresql.ENUM('ADMIN', 'STAFF', 'MEMBER', name='userrole'),
               existing_nullable=True)
    op.create_table('user_activity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('login_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('logout_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('session_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('browser', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_activity_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_activity_pkey')
    )
    op.create_index('ix_user_activity_id', 'user_activity', ['id'], unique=False)
    op.drop_index(op.f('ix_user_activities_id'), table_name='user_activities')
    op.drop_table('user_activities')
    # ### end Alembic commands ###
