"""Update UserRole Enum to uppercase

Revision ID: 7fc575a9bf3e
Revises: 2b6faaf3e73e
Create Date: 2025-02-11 23:21:13.120205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc575a9bf3e'
down_revision: Union[str, None] = '2b6faaf3e73e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
